### ISSUE TITLE
file /resource/regex.txt is not inexistence

### ISSUE THREAD

**Issue by wukui199272** [fighting41love/cocoNLP#3]

**Comment by fighting41love** [comment]
Could you pls show the code here?
The operating system is windows or Mac OS?
The version of python?
Thanks!

**Comment by yudong27** [comment]
same problem in class TimeNormalizer, the code 

> fpath = os.path.dirname(__file__) + '/resource/reg.pkl'
> try:
>      with open(fpath, 'rb') as f:
>             pattern = pickle.load(f)
>  except:
>      with open(os.path.dirname(__file__) + '/resource/regex.txt', 'r') as f:
>             content = f.read()

we get an exception(_RuntimeError: invalid RE code_), then regex.txt will be opened, but we get FileNotFoundError

**Comment by fighting41love** [comment]
> same problem in class TimeNormalizer, the code
> 
> > fpath = os.path.dirname(**file**) + '/resource/reg.pkl'
> > try:
> > with open(fpath, 'rb') as f:
> > pattern = pickle.load(f)
> > except:
> > with open(os.path.dirname(**file**) + '/resource/regex.txt', 'r') as f:
> > content = f.read()
> 
> In try, we get an exception(_RuntimeError: invalid RE code_), then regex.txt will be opened, but we get FileNotFoundError

On ubuntu, I can reproduce the bug.
On MacOS, the cocoNLP works well. 
The reason is the encoding format of regex.pkl. There are two solutions:
1. reinstall the new version (I have fixed the bug in verstion 0.0.10)
`
pip install cocoNLP==0.0.10
`
2. download the regex.txt in the following link first
https://github.com/fighting41love/cocoNLP/tree/master/cocoNLP/config/basic/time_nlp/resource
and save it to the site-packages directory, for instance:
`
~/anaconda3/lib/python3.6/site-packages/cocoNLP/config/basic/time_nlp/resources
`
